/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-05-22 07:15:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.search;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class graph_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"https://d3js.org/d3.v3.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/c3/0.4.11/c3.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".c3 svg {background-color:#ffffff !important}\r\n");
      out.write(".c3 text {fill: #000000; font:10px Arial;}\r\n");
      out.write(".c3-grid line {stroke: #000000 !important; }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var ChartProp={\"data\":{\"columns\":[[\"홈플\",\"10\"]\r\n");
      out.write(",[\"쿠팡\",\"12\"]\r\n");
      out.write(",[\"롯데마트\",\"11\"]\r\n");
      out.write(",[\"이마트\",\"13\"]\r\n");
      out.write("]\r\n");
      out.write(",\"type\":\"bar\"}\r\n");
      out.write(",\"color\":{}\r\n");
      out.write(",\"bar\":{\"width\":{\"ratio\":\"0.95\"}\r\n");
      out.write("}\r\n");
      out.write(",\"pie\":{}\r\n");
      out.write(",\"donut\":{}\r\n");
      out.write(",\"legend\":{\"show\":true,\"position\":\"bottom\"}\r\n");
      out.write(",\"tooltip\":{\"show\":true,\"grouped\":true}\r\n");
      out.write(",\"zoom\":{\"enabled\":false}\r\n");
      out.write(",\"transition\":{}\r\n");
      out.write(",\"point\":{\"show\":true}\r\n");
      out.write(",\"axis\":{\"rotated\":false,\"x\":{\"tick\":{}\r\n");
      out.write("}\r\n");
      out.write(",\"y\":{}\r\n");
      out.write("}\r\n");
      out.write(",\"grid\":{\"x\":{\"show\":true}\r\n");
      out.write(",\"y\":{\"show\":true}\r\n");
      out.write("}\r\n");
      out.write(",\"size\":{\"width\":\"500\",\"height\":\"400\"}\r\n");
      out.write(",\"padding\":{\"left\":30,\"top\":30,\"bottom\":0,\"right\":0}\r\n");
      out.write("}\r\n");
      out.write("window.onload=function(){\r\n");
      out.write("c3.generate(ChartProp);\r\n");
      out.write("var svg = d3.select('svg');\r\n");
      out.write("svg.append('text')\r\n");
      out.write("\t.attr('x', parseInt(svg.style('width'))/2)\r\n");
      out.write("\t.attr('y', 25)\r\n");
      out.write("\t.style({'text-anchor': 'middle', 'font-size': '30px', 'fill':'#000000'})\r\n");
      out.write("\t.text('마트 가격비교');\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"chart\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
